# Bug_Report.yaml v1.0.0.0
#
# CC BY-NC-SA 3.0 Unported 
#
# GitHub ISSUE_TEMPLATES
# by zer0Kerbal
#
# created: 13 Feb 2022
# updated: 
#
name: "Bug report 🐛"
description: Report errors or unexpected behavior🤔
title: "[Bug 🐞]: "
labels: ["bug"]
assignees:
  - zer0Kerbal
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome!
        >
        > Thanks for taking the time to fill out this Bug Report!
        > This bug tracker is monitored by @zer0Kerbal.
        > 
        >
        > Please use this form and describe your issue, concisely but precisely, with as much detail as possible.
  - type: textarea
    attributes:
      label: Brief description of your issue
      placeholder: Briefly describe your issue here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: A description of how to trigger this bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      placeholder: What is currently happening?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      placeholder: |
        Mod: Version
        KSP: Version
        Download/Installation: CurseForge/CurseForge App/GitHub clone/ GitHub release .zip/CKAN/SpaceDock
        KSP.log
      render: shell
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: How did you download and install this?
      options:
        - OverWolf/CurseForge App (auto install)
        - CKAN (auto install with dependencies)
        - CurseForge (download and manual installation)
        - SpaceDock (manual install)
        - GitHub clone (expert manual installation)
        - GitHub release .zip (advanced manual installation)
        - Built from source (add-ons only)
        - Other (explain below)
    validations:
      required: true
