# Bug_Report.yml v1.0.1.0
#
# CC BY-NC-ND 3.0 Unported 
#
# GitHub ISSUE_TEMPLATES
# by zer0Kerbal
#
# created: 13 Feb 2022
# updated: 12 Sept 2022
#
name: "Bug report ðŸ›"
description: Report errors or unexpected behaviorðŸ¤”
title: "[Bug ðŸž]: "
labels: ["bug"]
assignees:
  - zer0Kerbal
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome!
        >
        > Thanks for taking the time to fill out this Bug Report!
        > This bug tracker is monitored by @zer0Kerbal.
        > 
        >
        > Please use this form and describe your issue, concisely but precisely, with as much detail as possible.
  - type: textarea
    attributes:
      label: Brief description of your issue (aka the problem)
      description:
        Briefly describe your issue you are experiencing here. Kindly 
        provide a clear and concise description of what you were trying
        to do and what happened, along with any error messages you encountered.
      placeholder: 
        enter your description here.
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description:
        'Enter the specific operating system version you are running (example:
        Windows 10)'
    validations:
      required: false
  - type: input
    id: ksp-version
    attributes:
      label: KSP version
      description: what version of Kerbal Space Program
    validations:
        required: true
  - type: input
    id: addon-on-version
    attributes:
      label: Version of addon
      description:
        'Enter the specific addon version you are running (1.0.0.0-release)'
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the behavior or issue
      description: Provide steps to reproduce the behavior or issue you are experiencing.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error        
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual behavior
      placeholder: What is currently happening?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      placeholder: |
        Mod: Version
        KSP: Version
        Download/Installation: CurseForge/CurseForge App/GitHub clone/ GitHub release .zip/CKAN/SpaceDock
        KSP.log
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description:
        Please upload a log file from a day you experienced the issue. To access
        the log files go to the menu and select `Help` > `Show Logs`.
      placeholder:
        You can attach log files by clicking this area to highlight it and then
        dragging the files in.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem, if applicable.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Add any other context about the problem you are experiencing here.
  - type: dropdown
    id: download
    attributes:
      label: How did you download and install this?
      options:
        - OverWolf/CurseForge App (auto install)
        - CKAN (auto install with dependencies)
        - CurseForge (download and manual installation)
        - SpaceDock (manual install)
        - GitHub clone (expert manual installation)
        - GitHub release .zip (advanced manual installation)
        - Built from source (add-ons only)
        - Other (explain below)
    validations:
      required: true
