name: "Bug report 🐛"
description: Report errors or unexpected behavior🤔
title: "[Bug 🐞]: "
labels: ["bug"]
assignees:
  - zer0Kerbal
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome!
        >
        > Thanks for taking the time to fill out this Bug Report!
        > This bug tracker is monitored by @zer0Kerbal.
        > 
        >
        > Please use this form and describe your issue, concisely but precisely, with as much detail as possible.
  - type: textarea
    attributes:
      label: Brief description of your issue
      placeholder: Briefly describe your issue here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: A description of how to trigger this bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      placeholder: What is currently happening?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      placeholder: |
        [winget --info]
        Windows Package Manager version
        Windows: Windows.Desktop version
        Package: Microsoft.DesktopAppInstaller version

        Any other software?
      render: shell
    validations:
      required: true
