# config.yml v1.0.0.0
#
# CC BY-NC-ND 3.0 Unported 
#
# GitHub ISSUE_TEMPLATES
# by zer0Kerbal
#
# created: 13 Feb 2022
# updated: 
#
blank_issues_enabled: true
contact_links:  
  - name: General Question
    url: https://github.com/zer0Kerbal/zer0Kerbal/discussions/new
    about: Have a question on something? Start a new discussion thread.
  - name: Review open issues
    url: # https://github.com/zer0Kerbal/JoolianDiscovery/issues
    about: Please check if your issue or a similar issue has already been submitted
  - name: The Short List
    url: https://github.com/users/zer0Kerbal/projects/27
    about: The current list of current and planned projects
  - name: zer0Kerbal's Mod Tracker
    url: https://docs.google.com/spreadsheets/d/1zbLQg7NNHn4dYYaGy0a_MInkt2G_5PaN/edit#gid=1647283337
    about: Google Docs Spreadsheet of all of zer0Kerbals' mods and addons
  - name: Twitter @zer0Kerbal
    url: https://twitter.com/zer0Kerbal
    about: zer0Kerbal on twitter ![zer0Kerbal](https://simpleicons.org/icons/twitch.svg)
  - name: Kerbal Space Program's Forum
    url: https://forum.kerbalspaceprogram.com/index.php?/profile/190933-zer0kerbal/
    about: zer0Kerbal on Kerbal Space Program's Forum
  - name: Twitch
    url: https://www.twitch.tv/zer0kerbal
    about: zer0Kerbal's Twitch Channel
  - name: YouTube
    url: https://www.youtube.com/channel/UCp9c8IaK4Gjgfj3O9QxrbDw
    about: zer0Kerbal's YouTube Channel
  - name: Reddit
    url: https://www.reddit.com/user/zer0Kerbal
    about: zer0Kerbal Reddit
  - name: Patreon
    url: https://www.patreon.com/zer0Kerbal
    about: zer0Kerbal's Patreon Page
