# Documentation_Issue.yml v1.0.0.0
#
# CC BY-NC-ND 3.0 Unported 
#
# GitHub ISSUE_TEMPLATES
# by zer0Kerbal
#
# created: 13 Feb 2022
# updated: 
#
name: "Documentation Issue 📚"
description: Report issues in our documentation
title: "[Documentation Issue 📚]: "
labels: ["type: docs", "type: discussion"]
assignees:
  - zer0Kerbal
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome!
        Thanks for taking the time to fill out this Documentation Issue!
  - type: textarea
    attributes:
      label: Which document/file?
      placeholder: Briefly describe what needs to be corrected and why
    validations:
      required: true
  - type: textarea
    attributes:
      label: Brief description of your issue
      placeholder: Briefly describe which document needs to be corrected and why
    validations:
      required: true
